services:
  # Authentication server
  keycloak_db:
    image: postgres:14
    volumes:
      - ./.docker/db/keycloak/data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER=keycloak_u
      - POSTGRES_DB=keycloak
      - POSTGRES_HOST_AUTH_METHOD=trust # <=== danger only DEV
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    ports:
      - 7777:8080
    environment:
      # - KEYCLOAK_USER=admin <-- uncomment to add user on first run
      # - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak_db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak_u
    depends_on:
      - keycloak_db
    networks:
      default:
      static-network:
        ipv4_address: 172.21.32.54

  # Apisix Gateway
  apisix:
    image: apache/apisix:2.11.0-centos
    volumes:
      - ./apisix_config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080"
      - "9091:9091"
      - "9443:9443"
      - "9092:9092"
    networks:
      default:
      static-network:

  apisix-dashboard:
    image: apache/apisix-dashboard:2.10.1-centos
    restart: always
    volumes:
    - ./apisix_dashboard_conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    - "9000:9000"
    networks:
      static-network:

  etcd:
    image: bitnami/etcd:3.4.15
    volumes:
      - ./.docker/etcd_data:/bitnami/etcd:Z
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379"
    networks:
      default:
      static-network:

  # Kong Gateway
  # kong:
  #   image: kong:2.7.0-centos
  #   environment:
  #     KONG_DATABASE: "off"
  #     KONG_ADMIN_ACCESS_LOG: /dev/stdout
  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
  #     KONG_PROXY_LISTEN: 0.0.0.0:8000
  #     KONG_ADMIN_LISTEN: 0.0.0.0:8001
  #     KONG_PROXY_ACCESS_LOG: /dev/stdout
  #     KONG_PROXY_ERROR_LOG: /dev/stderr
  #     KONG_DECLARATIVE_CONFIG: /opt/kong/kong.yaml
  #   volumes:
  #     - ./kong.yaml:/opt/kong/kong.yaml:Z
  #   ports:
  #     - 8000:8000
  #     - 8443:8443
  #     - 8001:8001
  #     - 8444:8444
  #   networks:
  #     default:
  #     static-network:
networks:
  static-network:
    external: true
