services:
  deploy_clients:
    build:
      context: ../../
      dockerfile: ./docker/mseuser_deploy_client_libraries/deploy_clients.Dockerfile
    user: "${USER_ID}:${USER_GROUP_ID}"
    volumes:
      - ../../.:/opt/source/:Z
      - ${USER_HOME}/.m2/:/home/container_u/.m2/:Z
      - ${USER_HOME}/.gem/:/home/container_u/.gem/:Z
      - ${USER_HOME}/.npmrc:/home/container_u/.npmrc:Z