services:
  db:
    image: postgres:14
    volumes:
      - ../../.docker/db/test/data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER=container_u
      - POSTGRES_DB=mseuser_test
      - POSTGRES_HOST_AUTH_METHOD=trust # <=== danger only DEV

  spring_boot:
    build:
      context: ../../
      dockerfile: ./docker/mseuser_generate_api/spring_boot.Dockerfile
    user: "${USER_ID}:${USER_GROUP_ID}"
    volumes:
      - ../../.:/opt/source/:Z
    depends_on:
      - db